### ISSUE TITLE
Content visibility in %

### ISSUE THREAD

**Issue by EFXPROMedia** [patik/within-viewport#19]
How can we verify if the content in the viewport is 25% out or in the viewport.

I am looking to a way to add element classes when the element is 25% in the viewport and remove it when it its 25% out.

Please any suggestions?

**Comment by patik** [comment]
You may want to look into [`getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) to determine the location of your element on the page. Then you should be able to calculate 25% of its width and compare that to the viewport using `window.innerHeight` and `document.body.scrollTop`.

I'm closing the issue because I don't plan to support this feature in this project, but feel free to keep the discussion going if you need more info.
